### PR TITLE
Checklists for armor

### PR DESCRIPTION
**Pull request by AnandaNHN**
Hello,
Thanks for making this Bloodborne checklist.
I have added two more tabs with checklist for getting all armor pieces. One by type and one by sets
See this [link](https://anandanhn.github.io/bloodborne-cheat-sheet/)

### CODE REVIEW

**Comment by Duracell1989** [comment]
Shouldn't the data-id's on the third tab, be the same as on the fourth tab?
I mean: If I check the "Beak Mask" on the third tab - then I would expect that I 'have' it; thus, shouldn't it also be check on the fourth tab?

**Comment by AnandaNHN** [comment]
Yes that would be ideal and cool if it could work like that. 
Unfortunately I have no knowledge of how HTML or JavaScript or whatever it is written in works, so from looking at the code I could only reverse engineer how the basic headline, list, and checkbox structure worked.

**Comment by ZKjellberg** [comment]
Hi @AnandaNHN , Looking over your contribution, adding an armor checklist is nice, but I'm crazy about the redundancy. [For Dark Souls 3, we have a single Armor section](http://zkjellberg.github.io/dark-souls-3-cheat-sheet/).

Regarding @Duracell1989 's feedback, `Beak Mask` would need to use `armor_1_1` for both sections, whereas the Set Page uses `sets_8_1`, though would break your calculations for complete sets.

To merge this PR, I would prefer to condense this as a single TAB for Armor.

**Comment by AnandaNHN** [comment]
Okay, as far as I can see just changing the tag to the same in both places and putting it all in a single tab will not check both boxes when one is clicked so to avoid confusion there should probably only be either by type or sets.
So if i remove one tab which list would be preferred, type or set?

**Comment by Duracell1989** [comment]
> Okay, as far as I can see just changing the tag to the same in both places and putting it all in a single tab will not check both boxes when one is clicked so to avoid confusion there should probably only be either by type or sets.

I think that; if you check it in 1 place and refresh the page - then the second reference will (also) be checked. Thus; which item's are checked is only validated on the load of the page.

**Comment by ZKjellberg** [comment]
Though we organized by body armor type (which worked well with the search function), I think your arrangement for sets works better for Bloodborne.

If you can reduce this down to the Sets tab, we can merge it in.

**Comment by AnandaNHN** [comment]
Sounds good. One armor tab has been removed now

**Comment by ZKjellberg** [comment]
@AnandaNHN [Please fix the W3C HTML errors listed here](https://validator.w3.org/nu/?doc=https%3A%2F%2Fanandanhn.github.io%2Fbloodborne-cheat-sheet%2F)

Otherwise, looks good. I'll merge this soon after the fixes.

**Comment by ZKjellberg** [comment]
Pull Request #12 addresses the final request I had. I've merged the code in.

**Pull request closed without merging**
